// <auto-generated />
using System;
using GymHub.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymHub.Server.Data.Migrations
{
    [DbContext(typeof(GymHubDbContext))]
    [Migration("20260619133555_AddSessionStatusAndCompletedAt")]
    partial class AddSessionStatusAndCompletedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymHub.Server.Data.AppMeta", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_meta", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.BodyMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Arm")
                        .HasColumnType("double precision")
                        .HasColumnName("arm");

                    b.Property<double?>("Chest")
                        .HasColumnType("double precision")
                        .HasColumnName("chest");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<double?>("Hip")
                        .HasColumnType("double precision")
                        .HasColumnName("hip");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<double?>("Thigh")
                        .HasColumnType("double precision")
                        .HasColumnName("thigh");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<double?>("Waist")
                        .HasColumnType("double precision")
                        .HasColumnName("waist");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("idx_body_user_date");

                    b.ToTable("body_measurements", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_part");

                    b.Property<string>("BodyPartKo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("body_part_ko");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipment");

                    b.Property<string>("EquipmentKo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("equipment_ko");

                    b.Property<DateTimeOffset?>("GifCachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gif_cached_at");

                    b.Property<string>("GifLocalPath")
                        .HasColumnType("text")
                        .HasColumnName("gif_local_path");

                    b.Property<string>("GifUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gif_url");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameKo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("name_ko");

                    b.Property<string>("SecondaryMuscles")
                        .HasColumnType("text")
                        .HasColumnName("secondary_muscles");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<string>("TargetKo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("target_ko");

                    b.HasKey("Id");

                    b.HasIndex("BodyPart")
                        .HasDatabaseName("idx_exercises_body_part");

                    b.HasIndex("BodyPartKo")
                        .HasDatabaseName("idx_exercises_body_part_ko");

                    b.HasIndex("Equipment")
                        .HasDatabaseName("idx_exercises_equipment");

                    b.HasIndex("NameKo")
                        .HasDatabaseName("idx_exercises_name_ko");

                    b.HasIndex("Target")
                        .HasDatabaseName("idx_exercises_target");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.ExerciseNameOverride", b =>
                {
                    b.Property<string>("ExerciseId")
                        .HasColumnType("text")
                        .HasColumnName("exercise_id");

                    b.Property<string>("NameKo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ko");

                    b.HasKey("ExerciseId");

                    b.ToTable("exercise_name_overrides", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.InbodyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Bmi")
                        .HasColumnType("double precision")
                        .HasColumnName("bmi");

                    b.Property<double?>("Bmr")
                        .HasColumnType("double precision")
                        .HasColumnName("bmr");

                    b.Property<double?>("BodyFatPercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("body_fat_percentage");

                    b.Property<double?>("BodyWater")
                        .HasColumnType("double precision")
                        .HasColumnName("body_water");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<double?>("MuscleMass")
                        .HasColumnType("double precision")
                        .HasColumnName("muscle_mass");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("VisceralFat")
                        .HasColumnType("integer")
                        .HasColumnName("visceral_fat");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("idx_inbody_user_date");

                    b.ToTable("inbody_records", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.Profile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("UserId");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order_index");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_routines_user");

                    b.ToTable("routines", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.RoutineExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultReps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("default_reps");

                    b.Property<int>("DefaultSets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("default_sets");

                    b.Property<double>("DefaultWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("default_weight");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercise_id");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercise_name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int>("RoutineId")
                        .HasColumnType("integer")
                        .HasColumnName("routine_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId")
                        .HasDatabaseName("idx_routine_exercises_routine");

                    b.ToTable("routine_exercises", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSub")
                        .HasColumnType("text")
                        .HasColumnName("google_sub");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("GoogleSub")
                        .IsUnique()
                        .HasDatabaseName("idx_users_google_sub");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.WorkoutEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercise_id");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercise_name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int?>("RestSec")
                        .HasColumnType("integer")
                        .HasColumnName("rest_sec");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<int?>("SupersetGroup")
                        .HasColumnType("integer")
                        .HasColumnName("superset_group");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("idx_entries_exercise");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_entries_session");

                    b.HasIndex("Target")
                        .HasDatabaseName("idx_entries_target");

                    b.ToTable("workout_entries", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DurationSec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duration_sec");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("in_progress")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("idx_sessions_user_date");

                    b.ToTable("workout_sessions", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("completed");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer")
                        .HasColumnName("entry_id");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("set_number");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("idx_sets_entry");

                    b.ToTable("workout_sets", (string)null);
                });

            modelBuilder.Entity("GymHub.Server.Data.BodyMeasurement", b =>
                {
                    b.HasOne("GymHub.Server.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymHub.Server.Data.InbodyRecord", b =>
                {
                    b.HasOne("GymHub.Server.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymHub.Server.Data.Profile", b =>
                {
                    b.HasOne("GymHub.Server.Data.User", null)
                        .WithOne()
                        .HasForeignKey("GymHub.Server.Data.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymHub.Server.Data.Routine", b =>
                {
                    b.HasOne("GymHub.Server.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymHub.Server.Data.RoutineExercise", b =>
                {
                    b.HasOne("GymHub.Server.Data.Routine", "Routine")
                        .WithMany("Exercises")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("GymHub.Server.Data.WorkoutEntry", b =>
                {
                    b.HasOne("GymHub.Server.Data.WorkoutSession", "Session")
                        .WithMany("Entries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GymHub.Server.Data.WorkoutSession", b =>
                {
                    b.HasOne("GymHub.Server.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymHub.Server.Data.WorkoutSet", b =>
                {
                    b.HasOne("GymHub.Server.Data.WorkoutEntry", "Entry")
                        .WithMany("Sets")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("GymHub.Server.Data.Routine", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymHub.Server.Data.WorkoutEntry", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("GymHub.Server.Data.WorkoutSession", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
