using GymHub.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.DependencyInjection;

namespace GymHub.Server.Tests;

public sealed class GymHubMigrationsTests
{
    [Fact]
    public void InitialCreateMigrationIsRegistered()
    {
        using var context = new GymHubDbContextFactory().CreateDbContext([]);

        var migration = Assert.Single(context.Database.GetMigrations());

        Assert.EndsWith("InitialCreate", migration);
    }

    [Fact]
    public void MigrationScriptCreatesGymHubSchema()
    {
        using var context = new GymHubDbContextFactory().CreateDbContext([]);
        var migrator = context.GetInfrastructure().GetRequiredService<IMigrator>();

        var sql = migrator.GenerateScript();

        Assert.Contains("CREATE TABLE exercises", sql);
        Assert.Contains("CREATE TABLE workout_sessions", sql);
        Assert.Contains("CREATE TABLE workout_entries", sql);
        Assert.Contains("CREATE TABLE workout_sets", sql);
        Assert.Contains("CREATE TABLE body_measurements", sql);
        Assert.Contains("CREATE TABLE inbody_records", sql);
        Assert.Contains("CREATE TABLE app_meta", sql);
        Assert.Contains("CREATE TABLE exercise_name_overrides", sql);
        Assert.Contains("CREATE TABLE routines", sql);
        Assert.Contains("CREATE TABLE routine_exercises", sql);
    }

    [Fact]
    public void MigrationScriptUsesPostgresIdentityAndCascade()
    {
        using var context = new GymHubDbContextFactory().CreateDbContext([]);
        var migrator = context.GetInfrastructure().GetRequiredService<IMigrator>();

        var sql = migrator.GenerateScript();

        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", sql);
        Assert.Contains("ON DELETE CASCADE", sql);
        Assert.Contains("idx_entries_exercise", sql);
        Assert.Contains("idx_routine_exercises_routine", sql);
    }
}
