using GymHub.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.DependencyInjection;

namespace GymHub.Server.Tests;

public sealed class GymHubMigrationsTests
{
    [Fact]
    public void MigrationsAreRegisteredInOrder()
    {
        using var context = new GymHubDbContextFactory().CreateDbContext([]);

        var migrations = context.Database.GetMigrations().ToList();

        Assert.Equal(6, migrations.Count);
        Assert.EndsWith("InitialCreate", migrations[0]);
        Assert.EndsWith("AddUsersAndUserScoping", migrations[1]);
        Assert.EndsWith("AddProfiles", migrations[2]);
        Assert.EndsWith("AddEntryRestSec", migrations[3]);
        Assert.EndsWith("AddEntrySupersetGroup", migrations[4]);
        Assert.EndsWith("AddSessionStatusAndCompletedAt", migrations[5]);
    }

    [Fact]
    public void MigrationScriptCreatesUsersTableAndUserScoping()
    {
        using var context = new GymHubDbContextFactory().CreateDbContext([]);
        var migrator = context.GetInfrastructure().GetRequiredService<IMigrator>();

        var sql = migrator.GenerateScript();

        Assert.Contains("CREATE TABLE users", sql);
        Assert.Contains("user_id", sql);
        Assert.Contains("idx_sessions_user_date", sql);
    }

    [Fact]
    public void MigrationScriptCreatesGymHubSchema()
    {
        using var context = new GymHubDbContextFactory().CreateDbContext([]);
        var migrator = context.GetInfrastructure().GetRequiredService<IMigrator>();

        var sql = migrator.GenerateScript();

        Assert.Contains("CREATE TABLE exercises", sql);
        Assert.Contains("CREATE TABLE workout_sessions", sql);
        Assert.Contains("CREATE TABLE workout_entries", sql);
        Assert.Contains("CREATE TABLE workout_sets", sql);
        Assert.Contains("CREATE TABLE body_measurements", sql);
        Assert.Contains("CREATE TABLE inbody_records", sql);
        Assert.Contains("CREATE TABLE app_meta", sql);
        Assert.Contains("CREATE TABLE profiles", sql);
        Assert.Contains("CREATE TABLE exercise_name_overrides", sql);
        Assert.Contains("CREATE TABLE routines", sql);
        Assert.Contains("CREATE TABLE routine_exercises", sql);
    }

    [Fact]
    public void MigrationScriptUsesPostgresIdentityAndCascade()
    {
        using var context = new GymHubDbContextFactory().CreateDbContext([]);
        var migrator = context.GetInfrastructure().GetRequiredService<IMigrator>();

        var sql = migrator.GenerateScript();

        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", sql);
        Assert.Contains("ON DELETE CASCADE", sql);
        Assert.Contains("idx_entries_exercise", sql);
        Assert.Contains("idx_routine_exercises_routine", sql);
    }
}
